version: '2.4'
services:
  mysensors:
    build: .
    image: mysensorsmqtt
    container_name: mysensorsmqtt
    network_mode: "host"
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    command: /root/mysensors --broker=tcp://127.0.0.1:1883 -port /dev/ttyUSB0
    volumes:
      - type: bind
        source: ./mysensors-state
        target: /.mysensors-state

